config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'

  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get 'home/about' => 'homes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, optional: true

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters,if: :devise_controller?

    protected

    def after_sign_out_path_for(resource)
      root_path
    end

    def after_sign_in_path_for(resource)
	  user_path(current_user)
    end


  private
	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
	end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_url)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_url)
  end

  private
    def book_comment_params
      params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_url)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_url)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, ]

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'You have creatad book successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(id: current_user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title, class:'control-label' %>
    <%= f.text_field :title, class:'form-control input-sm' %>
  </div>

  <div class="form-group">
    <%= f.label :body, 'Opinion', class:'control-label' %>
    <%= f.text_area :body, class:'form-control input-sm' %>
  </div>

  <div class="form-group">
    <%= f.submit class:'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/books/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr><th></th><th>Title</th><th>Opinion</th><th></th><th></th></tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: 'no_image.jpg', size:'50x50' %>
        <% end %>
      </td>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.body %></td>
      <% if book.favorited_by?(current_user) %>
      <td>
        <%= link_to book_favorites_path(book), method: :delete do %>
          <i class="fa fa-heart" aria-hidden="true"></i>
          <%= book.favorites.count %>
        <% end %>
      </td>
      <% else %>
      <td>
        <%= link_to book_favorites_path(book), method: :post do %>
          <i class="fa fa-heart" aria-hidden="true"></i>
          <%= book.favorites.count %>
        <% end %>
      </td>
      <% end %>
      <td>コメント数：<%= book.book_comments.count %></td>

    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors_messages', errors: @book %>

    <%= form_with model: @book, class:'col-md-6' do |f| %>
      <div class="form-group">
        <%= f.label :title, class:'control-label' %>
        <%= f.text_field :title, class:'form-control input-sm' %>
      </div>

      <div class="form-group">
        <%= f.label :body, 'Opinion',class:'control-label' %>
        <%= f.text_area :body, class:'form-control input-sm' %>
      </div>

      <div class="form-group">
        <%= f.submit class:'btn btn-success' %>
      </div>
    <% end %>
    <div class="col-md-12">
      <%= link_to 'Show', book_path(@book) %>
      <span>|</span>
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors_messages', errors: @book %>

    <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
    <% end %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>


    <h2>User info</h2>
    <table class='table'>

    <%= render 'users/info', user: current_user %>

    </table>



    <h2 class="mt-3">New book</h2>
    <%= render 'books/new', book: @book %>
    </div>


   <div class='col-md-8 offset-md-1'>
    <h2>Books</h2>
    <table class='table table-hover table-inverse'>
    <%= render 'books/table', books: @books %>
   </div>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: @book.user %>


    <h2 class="mt-3">New book</h2>
    <%= render 'books/new', book: Book.new %>
  </div>

  <div class='col-md-8 offset-md-1'>
    <h2>Book detail</h2>
    <table class="table">
      <tr>
        <td>
          <%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback:'no_image.jpg', size:'50x50' %>
            <br>
            <%= @book.user.name %>
          <% end %>
        </td>
        <td><%= link_to @book.title, book_path(@book) %></td>
        <td><%= @book.body %></td>

        <% if @book.favorited_by?(current_user) %>
        <td>
          <%= link_to book_favorites_path(@book), method: :delete do %>
            <i class="fa fa-heart" aria-hidden="true"></i>
            <%= @book.favorites.count %>
        <% end %>
        </td>
        <% else %>
        <td>
          <%= link_to book_favorites_path(@book), method: :post do %>
            <i class="fa fa-heart" aria-hidden="true"></i>
            <%= @book.favorites.count %>
        <% end %>
        </td>
        <% end %>


        <td>
          <% if @user.id == current_user.id %>
            <%= link_to 'Edit', edit_book_path(@book), class:'btn btn-success btn-xs' %>
          </td>
          <td>
            <%= link_to 'Destroy', book_path(@book), method: :delete, data: {confirm: '本当に消しますか?'}, class:'btn btn-danger btn-xs' %>
          </td>
          <% end %>
      </tr>
    </table>
    <div>
      <h3>コメント数：<%= @book.book_comments.count %></h3>
      <table class="table">
      <% @book_comments.each do |book_comment| %>
        <tr>
          <td>
            <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, fallback:'no_image.jpg', size:'40x40' %>
            <br>
            <%= book_comment.user.name %>
          </td>
          <td><%= book_comment.comment %></td>
          <% if book_comment.user == current_user %>
            <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, class:'btn btn-danger btn-xs' %></td>
          <% else %>
            <td></td>
          <% end %>
        <tr>
      <% end %>
      </table>
      <%= form_with model: [@book, @book_comment] do |f| %>
        <div class="form-group">
          <%= f.label :comment, 'コメント', class:'control-label' %>
          <%= f.text_area :comment, class:'form-control input-sm', placeholder:'コメントをここに' %>
        </div>
        <div class="form-group">
          <%= f.submit '送信',class:'btn btn-primary btn-sm pull-right' %>
        </div>
        <% end %>
    </table>
  </div>
</div>

app/views/homes/about.html.erb
<h1><i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>

app/views/homes/index.html.erb
<div class="container">
  <div class="row">
		<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
    <% end %>

		<h1>Welcom to

		  <i class="fas fa-book"></i><strong>Bookers</strong>  !!

		  </h1>
		<p>In

		  <i class="fas fa-book"></i><strong>Bookers</strong>, <br>

		  	you can share and exchange your opinions , inpresiions , and emotions<br>

		  	about various books!
		</p>




			<div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%=link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>


          <%=link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>

        </div>
      </div>



	</div>
</div>

app/views/layouts/_errors_messages.html.erb
<div class="text-danger">
  <% if errors.errors.any? %>
    <h3><%= errors.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
    <% errors.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>

 <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li><%= link_to "Home", user_path(current_user), class: "fas fa-home nav-link text-light" %></li>
            <li><%= link_to "Users", users_path, class: "fas fa-users nav-link text-light"%></li>
            <li><%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light"%></li>
            <li><%= link_to "logout", destroy_user_session_path, method: :delete , class: "fas fa-sign-out-alt nav-link text-light" %></li>

          <% else %>
            <li><%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %></li>
            <li><%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %></li>
            <li><%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
            <li><%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>

          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

          <%= yield %>


    <footer>

      <p class="text-center"> CopyRight Infratop.inc</p>

    </footer>

  </body>

</html>

app/views/users/_info.html.erb
<table class="table">
  <tr>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: 'no_image.jpg', size:'100x100' %>
  </tr>
  <tr>
    <th>name</th>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <th>introduction</th>
    <td><%= user.introduction %></td>
  </tr>
</table>
<div class="row">
<%= link_to '', edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
</div>

app/views/users/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr><th>image</th><th>name</th><th></th></tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: 'no-image.jpg', size:'50x50' %></td>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <% if @user.errors.any? %>
      <%= @user.errors.count %>件のエラーが発生しました
      <% @user.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      <% end %>

  <h2>User info</h2>
  <%= form_with model: @user, class:'col-md-3' do |f| %>
    <div class="form-group">
      <%= f.label :name, class:'control-label' %>
      <%= f.text_field :name, class:'form-control input-sm' %>
    </div>

    <div class="form-group">
      <%= f.label :Image, class:'control-label' %>
      <%= f.attachment_field :profile_image %>
    </div>

    <div class="form-group">
      <%= f.label :introduction, class:'control-label' %>
      <%= f.text_area :introduction, class:'form-control introduction' %>
    </div>

    <div class="form-group">
      <%= f.submit class:"btn btn-secondary" %>
    </div>
  <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<main>
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>


      <h2>User info</h2>
      <table class='table'>

        <%= render 'users/info', user: @user %>

      </table>



      <h2 class="mt-3">New book</h2>
      <%= render 'books/new', book: @book %>

    </div>

    <div class='col-md-8 offset-md-1'>
  	  <table class="table table-sm user-index">
	  	  <h2>Users</h2>
        <thead>
          <th>image</th>
          <th>name</th>
          <th></th>
  	    </thead>
  	  	<tbody>
  	  	  <% @users.each do |user| %>
	  	  	<tr>
	  	  	  <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50' %></td>
	  	  	  <td><%= user.name %></td>
	  	  	  <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  	</tr>
  	  	  <% end %>
  	  	</tbody>
  	  </table>
  	 </div>
  </div>
</div>

app/views/users/show.html.erb
<main>
    <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
    <% end %>
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'users/info', user: @user %>



        <h2 class="mt-3">New book</h2>
        <%= render 'books/new', book: Book.new %>
        </div>


      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
        <%= render 'books/table', books: @books %>
      </div>
    </div>
</div>

</table>


</main>